name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/vondruska/speedtest
  
    steps:
    - uses: actions/checkout@v1
    
    - name: Docker login
      env:
        REGISTRY_PASSWORD: ${{secrets.CR_PAT}}
      run: docker login ghcr.io -u "vondruska" -p "$REGISTRY_PASSWORD" 
    
    - name: Build docker image
      run: docker build --pull -t "$IMAGE_NAME:latest" .
      if: github.ref == 'refs/heads/main'
      
    - name: Build docker image (branch)
      run: docker build --pull -t "$IMAGE_NAME:$GITHUB_SHA" .
      if: github.ref != 'refs/heads/main'

    - name: Push images
      run: docker push $IMAGE_NAME
