name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: docker.pkg.github.com/vondruska/docker-speedtest/docker-speedtest
  
    steps:
    - uses: actions/checkout@v1
    
    - name: Docker login
      env:
        REGISTRY_PASSWORD: ${{secrets.GITHUB_TOKEN}}
      run: docker login docker.pkg.github.com -u "vondruska" -p "$REGISTRY_PASSWORD" 
    
    - name: Build docker image
      run: docker build --pull -t "$IMAGE_NAME:latest" ./src/
      if: github.ref == 'refs/heads/master'
      
    - name: Build docker image (branch)
      run: docker build --pull -t "$IMAGE_NAME:$GITHUB_SHA" ./src/
      if: github.ref != 'refs/heads/master'

    - name: Push images
      run: docker push $IMAGE_NAME
